version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    privileged: true
    ports:
      - "2181:2181"
  
  kafka1:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka1
    privileged: true
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_PORT: 9092
      JMX_PORT: 9988
  kafka2:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka2
    privileged: true
    depends_on: [ zookeeper ]
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9093"
      KAFKA_PORT: 9093
      JMX_PORT: 9988
  kafka3:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka3
    privileged: true
    depends_on: [ zookeeper ]
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9094"
      KAFKA_LISTENERS: "PLAINTEXT://:9094"
      KAFKA_PORT: 9094
      JMX_PORT: 9988
