version: "2"
services:
  kafka-manager:
    image: kafkamanager/kafka-manager
    container_name: kafka-manager
    ports:
      - "19000:9000"
    external_links:  # 连接本compose文件以外的container
      - zk_kafka_kafka1_1
      - zk_kafka_kafka2_1
      - zk_kafka_kafka3_1
    environment:
      ZK_HOSTS: zk_kafka_zookeeper_1:2181
networks:
  default:
    external:
      name: zk_kafka_default