version: "2"
services:
  kafka-manager:
    image: kafkamanager/kafka-manager
    container_name: kafka-manager
    ports:
      - "19000:9000"
    external_links:  # 连接本compose文件以外的container
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: zookeeper:2181
networks:
  default:
    external:
      name: zkkafkadocker_default
